### ISSUE TITLE
Fix "silent disconnect" issue

### ISSUE THREAD

**Issue by benji7425** [benji7425/disharmony#3]
Every now and again a bot will appear offline in Discord, with no offline event or disconnect logs in the server. Discord.js still believes it's connected. Very annoying.

**Comment by benji7425** [comment]
I'm wondering if this was caused by some of the events I had disabled. Will need to test more to find out. See bba5c1620c47e36d4f7c335835d3c73f6a4db290.

**Comment by benji7425** [comment]
Moving this to in-progress as I believe it's fixed as of my comment above, but want to keep an eye on it for a short while longer before being sure.

**Comment by benji7425** [comment]
Beta has been up for a while with zero issues, though granted not with tons of users/activity. However my confidence in this being resolved is increasing, so I'm going to tentatively call this fixed. Can always come back to it later if it isn't.

**Comment by benji7425** [comment]
Looks like I spoke too soon, it's back :(

Bot offline but code still going, found the following error in debug.log. Looks like it's related to a websocket error of some kind.

```
[29822] [Thu, 30 May 2019 15:53:28 GMT] [DEBUG] [ws] [connection] Connecting to wss://gateway.discord.gg/?v=6&encoding=json
[29822] [Thu, 30 May 2019 15:53:28 GMT] [ERROR] Unhandled exception!
        Unhandled error. ([object Object])
        Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:178:17)
    at WebSocketConnection.onError (/home/benji/discord-activity-monitor/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/benji/discord-activity-monitor/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:189:13)
    at WebSocket.finalize (/home/benji/discord-activity-monitor/node_modules/ws/lib/websocket.js:185:12)
    at ClientRequest._req.on (/home/benji/discord-activity-monitor/node_modules/ws/lib/websocket.js:635:10)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by benji7425** [comment]
Looks to be related to [discord.js #2555](<https://github.com/discordjs/discord.js/issues/2555>)
